backstage:
  ingress:
    enabled: true
    annotations:
       route.openshift.io/termination: edge
    host: backstage.apps.templates-cluster.redhat.com

  commonAnnotations:
    argocd.argoproj.io/sync-wave: "5"

  backstage:
    image:
      registry: quay.io
      repository: ablock/backstage-keycloak
      tag: latest

    extraEnvVars:
      - name: 'APP_CONFIG_app_baseUrl'
        value: 'https://backstage.apps.templates-cluster.redhat.com'
      - name: 'APP_CONFIG_backend_baseUrl'
        value: 'https://backstage.apps.templates-cluster.redhat.com'
      - name: 'APP_CONFIG_backend_cors_origin'
        value: 'https://backstage.apps.templates-cluster.redhat.com'
    
    extraContainers:
      - name: oauth2-proxy
        env:
          - name: OAUTH2_PROXY_CLIENT_ID
            value: 'backstage'
            #value: '{{ required "Keycloak Client Secret is Required" .Values.keycloak.clientId }}'
          - name: OAUTH2_PROXY_CLIENT_SECRET
            value: 'x'
            #value: '{{ required "Keycloak Client Secret is Required" .Values.keycloak.clientSecret }}'
          - name: OAUTH2_PROXY_COOKIE_SECRET
            #value: '{{ default (randAlpha 32 | lower | b64enc) .Values.keycloak.cookieSecret }}'
            value: '99c5ohBdrrA04oa8DUq143EPcj24xlkW0GTuPmMOyPw='
          - name: OAUTH2_PROXY_OIDC_ISSUER_URL
            value: 'https://keycloak.apps.templates-cluster.redhat.com/realms/master'
            #value: 'https://keycloak-keycloak.apps.templates-cluster.redhat.com/auth/realms/master'
            # value: '{{ required "Keycloak Issuer URL is Required" .Values.keycloak.issuerUrl }}'
          - name: OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY
            value: 'true'
        ports:
          - name: oauth2-proxy
            containerPort: 4180
            protocol: TCP
        imagePullPolicy: IfNotPresent
        image: 'quay.io/oauth2-proxy/oauth2-proxy:latest'
        args:
          - '--provider=oidc'
          - '--email-domain=*'
          - '--upstream=http://localhost:7007'
          - '--http-address=0.0.0.0:4180'
          - '--skip-provider-button'
  
  service:
    ports:
      backend: 4180
      targetPort: oauth2-proxy

  postgresql:
    enabled: false
   #  auth:
   #    username: bn_backstage
   #    database: backstage
   #  primary:
   #    persistence:
   #      enabled: true

keycloak:
  service:
    type: ClusterIP
  auth:
    adminPassword: "123456"
  ingress:
    enabled: true
    annotations:
       route.openshift.io/termination: edge
    hostname: keycloak.apps.templates-cluster.redhat.com
