# Default values for mypod.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

username: bXl1c2Vy
password: bXlwYXNz
hostname: mypod-default.apps-crc.testing
replicaCount: 1

image:
  repository: registry.redhat.io/rhscl/httpd-24-rhel7
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

podAnnotations: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
