apiVersion: v1
kind: Secret
metadata:
  labels:
    clustertemplateinstance.openshift.io/name: myapp
    clustertemplateinstance.openshift.io/namespace: default
    clustertemplate.openshift.io/cluster-setup-secret: ""
  name: mypodsecret
type: Opaque
data:
  username: {{ .Values.username }}
  password: {{ .Values.password }}
