kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cr-{{ .Release.Namespace }}-{{ .Release.Name }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - secrets
      - pods
      - namespaces
  - verbs:
      - '*'
    apiGroups:
      - clustertemplate.openshift.io
    resources:
      - clustertemplateinstances
      - clustertemplateinstances/status
  - verbs:
      - '*'
    apiGroups:
      - argoproj.io
    resources:
      - applications
  - verbs:
      - '*'
    apiGroups:
      - cluster.open-cluster-management.io
    resources:
      - managedclusters
      - managedclustersets/join
  - verbs:
      - '*'
    apiGroups:
      - register.open-cluster-management.io
    resources:
      - managedclusters/accept

